times_per_week:
  weekday:
    male:
      0-9: 0.143
      9-15: 0.196
      15-19: 0.215
      19-31: 0.267
      31-51: 0.381
      51-66: 0.395
      66-86: 0.196
      86-100: 0.065
    female:
      0-9: 0.236
      9-15: 0.263
      15-19: 0.324
      19-31: 0.492
      31-51: 0.62
      51-66: 0.815
      66-86: 0.246
      86-100: 0.091
  weekend:
    male:
      0-9: 0.107
      9-15: 0.114
      15-19: 0.111
      19-31: 0.174
      31-51: 0.201
      51-66: 0.245
      66-86: 0.175
      86-100: 0.082
    female:
      0-9: 0.111
      9-15: 0.199
      15-19: 0.19
      19-31: 0.229
      31-51: 0.266
      51-66: 0.281
      66-86: 0.229
      86-100: 0.15
hours_per_day:
  weekday:
    male:
      0-65: 3
      65-100: 11
    female:
      0-65: 3
      65-100: 11
  weekend:
    male:
      0-100: 12
    female:
      0-100: 12
drags_household_probability: 0
neighbours_to_consider: 15
maximum_distance: 10
