times_per_week:
  weekday:
    male:
      0-9: 0.124
      9-15: 0.231
      15-19: 0.587
      19-31: 0.402
      31-51: 0.274
      51-66: 0.268
      66-86: 0.103
      86-100: 0.019
    female:
      0-9: 0.404
      9-15: 0.367
      15-19: 0.168
      19-31: 0.213
      31-51: 0.18
      51-66: 0.184
      66-86: 0.036
      86-100: 0.011
  weekend:
    male:
      0-9: 0.185
      9-15: 0.19
      15-19: 0.237
      19-31: 0.145
      31-51: 0.13
      51-66: 0.146
      66-86: 0.089
      86-100: 0.0
    female:
      0-9: 0.074
      9-15: 0.132
      15-19: 0.044
      19-31: 0.067
      31-51: 0.077
      51-66: 0.041
      66-86: 0.031
      86-100: 0.004
hours_per_day:
  weekday:
    male:
      0-65: 3
      65-100: 11
    female:
      0-65: 3
      65-100: 11
  weekend:
    male:
      0-100: 12
    female:
      0-100: 12
drags_household_probability: 0
neighbours_to_consider: 7
maximum_distance: 10
