times_per_week:
  weekday:
    male:
      0-9: 0.032
      9-15: 0.106
      15-19: 0.126
      19-31: 0.738
      31-51: 0.421
      51-66: 0.533
      66-86: 0.15
      86-100: 0.033
    female:
      0-9: 0.135
      9-15: 0.147
      15-19: 0.358
      19-31: 0.544
      31-51: 0.4
      51-66: 0.409
      66-86: 0.101
      86-100: 0.02
  weekend:
    male:
      0-9: 0.038
      9-15: 0.101
      15-19: 0.106
      19-31: 0.321
      31-51: 0.262
      51-66: 0.304
      66-86: 0.176
      86-100: 0.063
    female:
      0-9: 0.043
      9-15: 0.081
      15-19: 0.141
      19-31: 0.251
      31-51: 0.231
      51-66: 0.18
      66-86: 0.146
      86-100: 0.06
hours_per_day:
  weekday:
    male:
      0-65: 3
      65-100: 11
    female:
      0-65: 3
      65-100: 11
  weekend:
    male:
      0-100: 12
    female:
      0-100: 12
drags_household_probability: 0
neighbours_to_consider: 7
maximum_distance: 10
