times_per_week:
  weekday:
    male:
      0-9: 2.312
      9-15: 1.715
      15-19: 1.62
      19-31: 1.382
      31-51: 0.629
      51-66: 0.819
      66-86: 0.799
      86-100: 0.473
    female:
      0-9: 2.331
      9-15: 1.598
      15-19: 2.618
      19-31: 1.37
      31-51: 0.73
      51-66: 1.095
      66-86: 1.113
      86-100: 0.323
  weekend:
    male:
      0-9: 1.124
      9-15: 1.107
      15-19: 1.01
      19-31: 0.875
      31-51: 0.444
      51-66: 0.456
      66-86: 0.366
      86-100: 0.149
    female:
      0-9: 1.485
      9-15: 1.314
      15-19: 1.215
      19-31: 1.036
      31-51: 0.518
      51-66: 0.517
      66-86: 0.447
      86-100: 0.202
hours_per_day:
  weekday:
    male:
      0-65: 3
      65-100: 3
    female:
      0-65: 3
      65-100: 3
  weekend:
    male:
      0-100: 12
    female:
      0-100: 12
drags_household_probability: 0
residence_type_probabilities:
  # if a person can visit both,
  # with what probability will
  # that person visit one or the 
  # other.
  household: 0.66
  care_home: 0.34
