name: JUNE
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py39hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py39hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h98b2900_1
  - bottleneck=1.3.4=py39heec5a64_0
  - brotli=1.0.7=hc377ac9_0
  - brotlipy=0.7.0=py39h1a28f6b_1002
  - bzip2=1.0.8=h620ffc9_4
  - c-ares=1.18.1=h1a28f6b_0
  - ca-certificates=2022.4.26=hca03da5_0
  - certifi=2022.6.15=py39hca03da5_0
  - cffi=1.15.0=py39h22df2f2_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - chart-studio=1.1.0=pyh9f0ad1d_0
  - colorlover=0.3.0=py_0
  - coverage=6.3.2=py39h1a28f6b_0
  - cryptography=37.0.1=py39h834c97f_0
  - cufflinks-py=0.17.3=py_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py39hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h1192e45_0
  - giflib=5.2.1=h1a28f6b_0
  - h5py=3.6.0=py39h7fe8675_0
  - hdf5=1.12.1=h160e8cb_2
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - ipykernel=6.9.1=py39hca03da5_0
  - ipython=8.3.0=py39hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py39hca03da5_1
  - jinja2=3.0.3=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h1a28f6b_0
  - jsonschema=4.4.0=py39hca03da5_0
  - jupyter_client=7.2.2=py39hca03da5_0
  - jupyter_core=4.10.0=py39hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.2=py39hc377ac9_0
  - krb5=1.19.2=h3b8d789_0
  - lcms2=2.12=hba8e193_0
  - libcurl=7.82.0=hc6d1d07_0
  - libcxx=12.0.0=hf6beb65_1
  - libedit=3.1.20210910=h1a28f6b_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.2=hc377ac9_4
  - libgfortran=5.0.0=11_2_0_he6877d6_26
  - libgfortran5=11.2.0=he6877d6_26
  - libllvm11=11.1.0=h12f7ac0_4
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.20=hea475bc_0
  - libpng=1.6.37=hb8d0fd4_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=hf27765b_0
  - libtiff=4.2.0=h01837e1_1
  - libwebp=1.2.2=h68602c7_0
  - libwebp-base=1.2.2=h1a28f6b_0
  - libzlib=1.2.12=ha287fd2_1
  - llvm-openmp=12.0.0=haf9daa7_1
  - llvmlite=0.38.0=py39h98b2900_0
  - lz4-c=1.9.3=hc377ac9_0
  - lzo=2.10=h1a28f6b_2
  - markupsafe=2.1.1=py39h1a28f6b_0
  - matplotlib=3.5.1=py39hca03da5_1
  - matplotlib-base=3.5.1=py39hc377ac9_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h1a28f6b_1000
  - mock=4.0.3=pyhd3eb1b0_0
  - munkres=1.1.4=py_0
  - nbclient=0.5.13=py39hca03da5_0
  - nbconvert=6.4.4=py39hca03da5_0
  - nbformat=5.3.0=py39hca03da5_0
  - ncurses=6.3=h1a28f6b_2
  - nest-asyncio=1.5.5=py39hca03da5_0
  - notebook=6.4.11=py39hca03da5_0
  - numba=0.55.1=py39h9197a36_0
  - numexpr=2.8.1=py39h144ceef_2
  - numpy=1.21.5=py39h42add53_3
  - numpy-base=1.21.5=py39hadd41eb_3
  - openssl=1.1.1o=h1a28f6b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.0.1=py39h4d1bdd5_0
  - pip=21.2.4=py39hca03da5_0
  - pluggy=1.0.0=py39hca03da5_1
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py39h1a28f6b_0
  - pysocks=1.7.1=py39hca03da5_0
  - pytables=3.7.0=py39h701507b_0
  - pytest-cov=3.0.0=pyhd3eb1b0_0
  - python=3.9.13=hc596b02_0_cpython
  - python-cufflinks=0.17.3=py_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.15.1=pyhd3eb1b0_0
  - pytz=2022.1=py39hca03da5_0
  - pyyaml=6.0=py39h1a28f6b_0
  - pyzmq=22.3.0=py39hc377ac9_2
  - readline=8.1.2=h1a28f6b_1
  - responses=0.13.3=pyhd3eb1b0_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - scikit-learn=1.0.2=py39h9197a36_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=61.2.0=py39hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sqlite=3.38.5=h1058600_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=h525c30c_0
  - tenacity=8.0.1=py39hca03da5_0
  - terminado=0.13.1=py39hca03da5_0
  - testpath=0.6.0=py39hca03da5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=hb8d0fd4_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=1.2.2=pyhd3eb1b0_0
  - tornado=6.1=py39h1a28f6b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.9=py39hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hca03da5_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py39hca03da5_0
  - xz=5.2.5=h1a28f6b_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.12=ha287fd2_1
  - zstd=1.5.2=h8574219_0
  - pip:
    - chardet==4.0.0
    - et-xmlfile==1.1.0
    - geographiclib==1.52
    - geopy==2.2.0
    - googlemaps==4.4.5
    - idna==2.10
    - mpi4py==3.1.3
    - networkx==2.8.4
    - openpyxl==3.0.9
    - pandas==1.4.1
    - plotly==4.14.3
    - pytest==7.1.1
    - recordclass==0.17.2
    - requests==2.25.1
    - scipy==1.8.0
    - score-clustering==0.1.4
    - sortedcontainers==2.4.0
    - tqdm==4.63.1
    - xlrd==2.0.1
