quarantine:
        n_days: 7 # for the symptomatic person
        n_days_household: 14 # for the housemates
        start_time: 2020-03-16 
        end_time: 2020-07-04 

shielding:
        min_age: 80
        start_time: 2020-03-16 
        end_time: 2020-07-04 

close_companies:
        start_time: 2020-03-16
        end_time: 2020-07-04 #TODO: Until when really?
        full_closure: False 

social_distancing:
        start_time: 2020-03-16
        end_time: 2020-07-04 #TODO: end time?
        beta_factor:
                box: 0.25
                pub: 0.25
                grocery: 0.25
                cinema: 0.25
                commute_unit: 0.25
                commute_city_unit: 0.25
                hospital: 0.25
                care_home: 0.25
                company: 0.25
                school: 0.25
                household: 1.0
                university: 0.25

close_leisure_venue:
        start_time: 2020-03-21
        end_time: 2020-07-04 #TODO: end time ?
        venues_to_close: ['pub', 'cinema', 'care_home_visit'] 
        #TODO: household_visits?
        #

        #change_leisure_probability:
        #        start_time: 2020-03-21
        #        end_time: 2020-07-04
        #        leisure_activities_probabilities:
        #          household_visits:
        #            men: 
        #              0-64: 0.054
        #              65-100: 0.0
        #            women: 
        #              0-64: 0.054
        #              65-100: 0.0

close_schools:
        start_time: 2020-03-20
        end_time: 2020-07-04 #TODO: end time?
        years_to_close: all
        full_closure: False

close_universities:
        start_time: 2020-03-20
        end_time: 2020-07-04
