hospitalisation:
    start_time: 1000-01-01
    end_time: 9999-01-01

severe_symptoms_stay_home:
    start_time: 1000-01-01
    end_time: 9999-01-01

quarantine:
    1:
        n_days: 7 # for the symptomatic person
        n_days_household: 14 # for the housemates
        compliance: 0.5 
        household_compliance: 0.2
        start_time: 2020-03-16 
        end_time: 2020-03-23 
    2:
        n_days: 7 # for the symptomatic person
        n_days_household: 14 # for the housemates
        compliance: 0.95 # for the symptomatic individual - needs to be checked
        household_compliance: 0.9
        start_time: 2020-03-23
        end_time: 2021-07-04

shielding:
    1:
        min_age: 70
        compliance: 0.2
        start_time: 2020-03-16 
        end_time: 2020-03-23
    2:
        min_age: 70
        compliance: 0.7
        start_time: 2020-03-23
        end_time: 2020-06-01


close_companies:
    1:
        start_time: 2020-03-16
        end_time: 2020-03-20
        full_closure: False 
        avoid_work_probability: 0.20 # prob of avoiding workplace if still working (YouGov)
        furlough_probability: 0.04 # prob of being furloughed (Statista)
        key_probability: 0.22 # prob of being a key worker (ONS)
    2:
        start_time: 2020-03-20
        end_time: 2020-03-27
        full_closure: False 
        avoid_work_probability: 0.29
	furlough_probability: 0.04
        key_probability: 0.22
    3:
        start_time: 2020-03-27
        end_time: 2020-04-17
        full_closure: False 
        avoid_work_probability: 0.38
	furlough_probability: 0.04
        key_probability: 0.22
    4:
        start_time: 2020-04-17
        end_time: 2020-05-01
        full_closure: False 
        avoid_work_probability: 0.36
	furlough_probability: 0.1
        key_probability: 0.22
    5:
        start_time: 2020-05-01
        end_time: 2020-05-15
        full_closure: False 
        avoid_work_probability: 0.35
	furlough_probability: 0.25
        key_probability: 0.22
    6:
        start_time: 2020-05-15
        end_time: 2020-06-16
        full_closure: False 
        avoid_work_probability: 0.31
	furlough_probability: 0.30
        key_probability: 0.22
    7:
        start_time: 2020-06-16
        end_time: 2020-07-12
        full_closure: False 
        avoid_work_probability: 0.25
	furlough_probability: 0.33
        key_probability: 0.22
    8:
        start_time: 2020-07-12
        end_time: 2020-07-26
        full_closure: False 
        avoid_work_probability: 0.21
	furlough_probability: 0.34
        key_probability: 0.22
    9:
        start_time: 2020-07-26
        end_time: 2020-08-07
        full_closure: False 
        avoid_work_probability: 0.20
	furlough_probability: 0.34
        key_probability: 0.22

social_distancing:
    1: 
        start_time: 2020-03-16
        end_time: 2020-03-23 
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            commute_unit: 0.875
            commute_city_unit: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875

    2:
        start_time: 2020-03-23
        end_time: 2020-07-04 
        beta_factors:
            box: 0.75
            pub: 0.75
            grocery: 0.75
            cinema: 0.75
            commute_unit: 0.75
            commute_city_unit: 0.75
            hospital: 0.75
            care_home: 0.75
            company: 0.75
            school: 0.75
            household: 1.0
            university: 0.75

mask_wearing:
    1: 
        start_time: 2020-03-27
        end_time: 2020-04-24
        compliance: 0.09 # overall mask wearing compliance (YouGov)
        beta_factor: 0.5 # overall beta reducion if mask wearing
        mask_probabilities: # given a mask is work, probability of where it is worn
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    2: 
        start_time: 2020-04-24
        end_time: 2020-05-21
        compliance: 0.17
        beta_factor: 0.5
        mask_probabilities:
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    3: 
        start_time: 2020-05-21
        end_time: 2020-06-16
        compliance: 0.23
        beta_factor: 0.5	
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    4: 
        start_time: 2020-06-16
        end_time: 2020-06-25
        compliance: 0.29
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    5: 
        start_time: 2020-06-25
        end_time: 2020-07-12
        compliance: 0.35
        beta_factor: 0.5	
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    6: 
        start_time: 2020-07-12
        end_time: 2020-07-26
        compliance: 0.48
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5
    7: 
        start_time: 2020-07-26
        end_time: 2020-07-31
        compliance: 0.63
        beta_factor: 0.5	
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 0.5
            cinema: 0.
            commute_unit: 1.
            commute_city_unit: 1.
            hospital: 0.
            care_home: 0.5
            company: 0.5
            school: 0.
            household: 0.
            university: 0.5

close_leisure_venue:
    start_time: 2020-03-21
    end_time: 2020-07-04 
    venues_to_close: ['pub', 'cinema', 'care_home_visit'] 

change_leisure_probability:
    start_time: 2020-03-23
    end_time: 2020-07-04
    leisure_activities_probabilities:
        household_visits:
            men: 
                0-64: 0.50
                65-100: 0.25
            women: 
                0-64: 0.50
                65-100: 0.25
        care_home_visits:
            men:
                0-100: 0.05
            women:
                0-100: 0.05

close_schools:
    start_time: 2020-03-20
    end_time: 2020-07-04 #TODO: end time? - this needs to be fixed as schools were partially opening before this
    years_to_close: all
    full_closure: False

close_universities:
    start_time: 2020-03-20
    end_time: 2020-10-01
