male_age_probabilities:
  0-65 : 0.37
  65-80 : 0.30
  80-100: 0.0
female_age_probabilities:
  0-65 : 0.37
  65-80 : 0.30
  80-100: 0.0
weekend_boost: 1
drags_household_probability: 1.0
# source
#https://www.ageuk.org.uk/globalassets/age-uk/documents/reports-and-publications/reports-and-briefings/health--wellbeing/rb_june15_lonelines_in_later_life_evidence_review.pdf
# 17 % of the old people have less than weekly contact
# 11 % less than monthly
# we assume that each person with a relative in a households has
# a 7% probability of visiting a relative there.
# This gives a weekly probability of 38% and 89% monthly
