name: Run linting and sanity checks

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install openmpi
      run: |
        sudo apt-get update -y
        sudo apt-get install -y openmpi-bin
        sudo apt install libopenmpi-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
        pip install black
    - name: Lint with black and flake8
      run: |
        black --check
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --show-source --statistics
        # flake8 .
    - name: Get JUNE data
      run: bash scripts/get_june_data.sh

    - name: Install simulation
      run: python setup.py install

    - name: Test with pytest
      run: |
        cd test_june
        pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS,PYTHON

    - name: Test all cells in ipynb for errors
      run: |
        jupyter nbconvert --to notebook --inplace --execute Notebooks/quickstart.ipynb
